### ISSUE TITLE
[BUG] MQTT viewer consumes disk space

### ISSUE THREAD

**Issue by PFigs** [wirepas/backend-client#103]
This report needs to be investigated further, but it seems that after a few weeks of running, the MQTT viewer has consumed quite a bit of disk space. There might be a queue that needs pruning.

**Comment by jsponz** [comment]
Could you tell me how you run it? 

I can't :-( 

Thanks!

**Comment by PFigs** [comment]
Hi @jsponz,

Have you followed the steps on the main readme file? 

If you are having problems, could you open a new issue and describe those? 

Thanks!

**Comment by jsponz** [comment]
Yes, I did.

But I was able to fix my issues (issue #107). Thanks!

**Comment by PFigs** [comment]
Closing as we cannot replicate it anymore.
