### ISSUE TITLE
How to run the examples?

### ISSUE THREAD

**Issue by jsponz** [wirepas/backend-client#107]
I have installed the package: 

pip install wirepas-backend-client

and everything ok. 

When trying to run the example:

python3 mqtt_viewer.py --settings ./.settings.yml

I get this message: 

Traceback (most recent call last):
  File "mqtt_viewer.py", line 6, in <module>
    import wirepas_backend_client
ModuleNotFoundError: No module named 'wirepas_backend_client'

What have I made wrong? 

Thanks!

**Comment by jsponz** [comment]
Update: I was wrong with the Python version. 

Now when I type:

python3 mqtt_viewer.py --settings ./.settings.yml

I get this: 

Traceback (most recent call last):
  File "mqtt_viewer.py", line 13, in <module>
    from wirepas_backend_client.tools.utils import deferred_thread
ImportError: cannot import name 'deferred_thread

**Comment by jsponz** [comment]
Python 3.7 solves everything.

**Comment by PFigs** [comment]
Thanks! @jsponz
