### ISSUE TITLE
Make MQTT settings parser more robust, allow anonymous-authentication

### ISSUE THREAD

**Issue by AlexFazakas** [wirepas/backend-client#127]
### Problem
As seen [here](https://github.com/wirepas/backend-client/blob/master/wirepas_backend_client/api/mqtt/settings.py#L68), unless you provide these 4 parameters, the backend will stop, which I don't think is clear enough and fully necessary.

### Suggestion
It would be nice to have a way of knowing what's wrong, instead of only printing a message [such as here](https://github.com/wirepas/backend-client/blob/master/wirepas_backend_client/cli.py#L1197).

Furthermore, some MQTT brokers support anonymous authentication ([for instance](https://github.com/beerfactory/hbmqtt/blob/master/samples/broker_acl.py#L22)), so I don't think username and password should be mandatory if some `--allow_anonymous_authentication` option would be provided. Instead, maybe use some default ones like `user` and `password` if none are provided?

**Comment by PFigs** [comment]
Hi @AlexFazakas ,

Thanks for pointing this out! 

We can certainly improve the error message to offer a better experience. Do you have a suggestion on what you would like to see? 

What do you think of:

```
Please review your connection settings:
Username: someuser
Password: set or not set (I would not like to print the password string)
Port: 8883
Accept unsecure: True or False
```

With regards to having a default username and password, we opted to leave them set to None to force the end user to use something else than default strings.

**Comment by AlexFazakas** [comment]
Hi @PFigs , thank you for having a look.

> ```
> Please review your connection settings:
> Username: someuser
> Password: set or not set (I would not like to print the password string)
> Port: 8883
> Accept unsecure: True or False
> ```

This would be a good change, but there's still nothing mentioning that all of these are mandatory. If there's no password field in the settings file, do you just print "not set"? Maybe adding a "(required)" next to these 4 parameters would be nice, what do you think?

> With regards to having a default username and password, we opted to leave them set to None to force the end user to use something else than default strings.

So are there no plans to allow anonymous authentication? In my case, I used a dummy username and password, but that doesn't feel nice given that I'm in no way using them on my broker.

**Comment by PFigs** [comment]
Hi @AlexFazakas ,

The error message will now identify which inputs are required and optional (see https://github.com/wirepas/backend-client/pull/128)

I will create a separate issue to track the anonymous authentication.
