### ISSUE TITLE
'InfluxSettings' object has no attribute 'sanity'

### ISSUE THREAD

**Issue by bvesperman** [wirepas/backend-client#139]
**Describe the bug**
I attempted to run the InfluxViewer but it failed for me. 

**To Reproduce**
1. I cloned the backend-client project
2. I installed the backend-client from pip:
https://pypi.org/project/wirepas-backend-client/
`pip install wirepas-backend-client`
3. Modified the settings.yml file in the examples folder for some real values for a wirepas WNT instance:

```
influx_database=wirepas
influx_port=8086
influx_hostname=<revoked>
influx_username=<revoked>
influx_password=<revoked>
```

4. I attempted to run the script:

```
backend-client/examples$ python3 influx_viewer.py --settings settings.yml
Invalid -W option ignored: invalid module name: 'yaml'
/usr/local/lib/python3.6/dist-packages/wirepas_backend_client/tools/arguments.py:65: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  settings = yaml.load(f)
Traceback (most recent call last):
  File "influx_viewer.py", line 165, in <module>
    if SETTINGS.sanity():
AttributeError: 'InfluxSettings' object has no attribute 'sanity'

```

**Conclusion**
I don't see a sanity function in:
wirepas_backend_client/api/influx/settings.py

but I do in:
wirepas_backend_client/api/wpe/settings.py

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04.1

**Comment by PFigs** [comment]
Hi!

Thanks for your report!

Which version did you pull from pip? Do you have this issue with the pre-release 3?

pip install wirepas-backend-client==1.2.0rc3

Cheers

**Comment by bvesperman** [comment]
I did 1.1.0.  I will give that a shot and see if it fixes my issue.

Brian V
