### ISSUE TITLE
ImportError: Unable to import required dependencies: numpy

### ISSUE THREAD

**Issue by jjuhola64** [wirepas/backend-client#198]
**Describe the bug**
I cloned wm-backend-client from Githut and installed with python3 -e .
Trying to run wm-gw-cli produces the import error message in title.
Full output enclosed.
I did user Rasberry Pi 4 with Raspbian lite.

**Expected behavior**
wm-gw-cli should start normally

** Fix **
based on Google study I find solution proposal:
sudo apt-get install libatlas-base-dev
adding this libarary solved my issue.
Should it be added to the dependencies?

**To Reproduce**
  101  virtualenv wm_bcli_env
  103  source wm_bcli_env/bin/activate
  104  python --version
  105  git clone https://github.com/wirepas/backend-client.git
  107  cd backend-client/
  108  git checkout 9a80f9e
  109  pip3 install -e .
  110 nano settings.yml
  111 gw-wm-cli --settings settings.yml    # - not ok
  123 sudo apt-get install libatlas-base-dev
  124 gw-wm-cli --settings settings.yml  # - OK

**Software versions:**
 - OS: raspbian-buster-lite (2019-09-26-raspbian-buster-lite)
            PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
            NAME="Raspbian GNU/Linux"
            VERSION_ID="10"
            VERSION="10 (buster)"

 - Python version: Python 3.7.3
 - Docker engine:  not used to install wm-backend-client
   (Docker version 19.03.5, build 633a0ea installed on same Raspi, running MQTT broker wm-broker,
   installed using from Tutorials/mqtt guidelines)

**Additional context**

For some reason first pip3 install -e . produced error message:
---
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
		    grpcio==1.22.0 from https://www.piwheels.org/simple/grpcio/grpcio-1.22.0-cp37-cp37m-linux_armv7l.whl#sha256=6f92b984a746341529b8f82f7c6e101d36d70764f232505949828af7dca27e06 (from wirepas-messaging==1.2.0->wirepas-backend-client==1.2.1):
		        Expected sha256 6f92b984a746341529b8f82f7c6e101d36d70764f232505949828af7dca27e06
             Got        18b29f0726d15e053c5eb4d21641d35ba6fa5ee536d433cded5014bc2c745ad3
---
But giving command 2nd time all compiled without any errors.
**Error message**
[wm-wg-cli-error.txt](https://github.com/wirepas/backend-client/files/4045654/wm-wg-cli-error.txt)

**Comment by PFigs** [comment]
Hi @jjuhola64 ,

Thanks for calling our attention to this. It is likely arm specific. 

We'll look into adding a arm build into our ci and document any extra dependency needed.

If you want to contribute, feel free to send a PR where you install backend-client within an ARM docker base image (please refer to our gateway repo for an example).

Best regards,

**Comment by ErkkiSalonenW** [comment]
Current plan is to support linux x86 version only.
