### ISSUE TITLE
Mesh Management redesign

### ISSUE THREAD

**Issue by PFigs** [wirepas/backend-client#21]
The MeshManagement class needs attention in order to simplify the access to the devices and improve memory usage.

#### Major issues to address: 
- Information is duplicated
- No index possible obj[index]

https://github.com/wirepas/backend-client/blob/e8ace9d96a994d4dfd6e0f4dd1e3f5237fb34062/wirepas_backend_client/management/network.py#L616

**Comment by ErkkiSalonenW** [comment]
Won't be implemented as out of scope.
