### ISSUE TITLE
Mesh Device missing methods

### ISSUE THREAD

**Issue by PFigs** [wirepas/backend-client#22]
The Mesh device is meant to be an abstraction of WM's remote apis. Currently we are lacking quite a few methods and attributes.

https://github.com/wirepas/backend-client/blob/e8ace9d96a994d4dfd6e0f4dd1e3f5237fb34062/wirepas_backend_client/management/network.py#L362

**Comment by ErkkiSalonenW** [comment]
Won't be implemented as out of scope.
