### ISSUE TITLE
[BUG] WM-GW-CLI indexing problem with sink listing

### ISSUE THREAD

**Issue by kahaapal** [wirepas/backend-client#250]
**Describe the bug**
Current behavior:

12:04.30 | wm-gw-cli > set_gateway
0 :nuc104:GatewayState.ONLINE
1 :nuc19:GatewayState.ONLINE
2 :53447165847351:GatewayState.ONLINE
3 :nuc44:GatewayState.ONLINE
4 :lt11:GatewayState.ONLINE
5 :nuc103:GatewayState.ONLINE
6 :nuc108:GatewayState.ONLINE
7 :nuc116:GatewayState.ONLINE
8 :nuc18:GatewayState.ONLINE
9 :nuc105:GatewayState.ONLINE
10 :nuc107:GatewayState.ONLINE
11 : custom gateway id
Please enter your gateway selection [0]:

If I select e.g.5, meaning nuc103, why on earth it still lists all possible sinks, under completely different NUCs:

13:24.06 | wm-gw-cli:nuc103:sink0 > set_sink
0 :1456854:nuc105:sink1
1 :1456854:nuc105:sink0
2 :1456854:nuc105:sink4
3 :1456854:nuc105:sink3
4 :1456854:nuc105:sink8
5 :1456854:nuc105:sink2
6 :1456854:nuc105:sink9
7 :1456854:nuc105:sink5
8 :1456854:nuc105:sink6
9 :1456854:nuc105:sink7
10 :1181108:lt11:sink0
11 :9780601:nuc107:sink0
12 :9780601:nuc107:sink1
13 :7799123:nuc116:sink0
14 :1199123:nuc108:sink0
15 :2864665:nuc44:sink0
16 :4672099:nuc103:sink0
17 :110600:53447165847351:sink0
18 :7392709:nuc18:sink0
19 : custom sink id

Here comes the biggest problem, when trying to select NW 16, having nuc103:
Please enter your sink selection [0]: 16

It will print the selection as I desired, but command goes to completely wrong NW:
13:24.15 | wm-gw-cli:nuc103:sink0 > send_data 255 240 23 610e20a10700b8d389000408fb507664
{'gw_id': 'nuc44', 'sink_id': 'sink0', 'req_id': 16598172802118484253, 'res': <GatewayResultCode.GW_RES_OK: 0>}

Making this tool somewhat completely useless.

**Expected behavior**
Response should come from GW where the command was intended to be sent, this case nuc103

**To Reproduce**
1. start wm-gw-cli
2. set_gateway
3. set_sink
4. send command

**Software versions:**
 - OS: Debian 10
 - Python version: 3.7

**Comment by ErkkiSalonenW** [comment]
Started checking this one. I think when applying command "set_" then filter should be applied to commands such as 'sinks', 'networks', 'nodes' and 'gateways' too. 

Open question is that is user have applied "MQTT filter" into settings.yml, how this should be applied when using commands.

**Comment by kahaapal** [comment]
When / if filter is applied, it would be great to filter out all other NWs.

**Comment by ErkkiSalonenW** [comment]
Fix done. Lets test for a while before release.

**Comment by ErkkiSalonenW** [comment]
Added to v1.3.3-rc.2
