### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by ozanoner** [wirepas/backend-client#255]
**Broken link**
Please replace cli.py links in the README.md file. No such file anymore and github returns 404

**Screenshots**
![Screenshot from 2020-02-13 10-36-22](https://user-images.githubusercontent.com/6412075/74427240-9d32f700-4e4e-11ea-890f-3bf577c8212f.png)
![Screenshot from 2020-02-13 10-44-53](https://user-images.githubusercontent.com/6412075/74427241-9dcb8d80-4e4e-11ea-83a3-74d98e634af6.png)

**Comment by ErkkiSalonenW** [comment]
Fix done. In review now.

**Comment by ErkkiSalonenW** [comment]
Added to v1.3.3-rc.2
