### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by florean-wirepas** [wirepas/backend-client#268]
**Describe the bug**
On the page https://github.com/wirepas/backend-client some of the links are broken.
E.g. 'wm-gw-cli' 

**Expected behavior**

**To Reproduce**

**Software versions:**

**Additional context**

**Screenshots**

**Comment by ErkkiSalonenW** [comment]
Will be taken into fix queue.

**Comment by ErkkiSalonenW** [comment]
Some links fixed.
