### ISSUE TITLE
[BUG] WM-GW-CLI gives timeout for NEIGH diag setting

### ISSUE THREAD

**Issue by kahaapal** [wirepas/backend-client#270]
**Describe the bug**
Seems that 30s timeout is not enough, at least in 1000 devices dense NW

**Expected behavior**

**To Reproduce**

18:09.47 | wm-gw-cli > set_gateway
Listing current online gateways:
0 :lt11
1 :nuc103
2 :nuc104
3 :nuc105
4 :nuc106
5 :nuc107
6 :nuc116
7 :nuc18
8 :nuc19
9 :nuc44
10 : custom gateway id
Please enter your gateway selection [0]: 3
18:09.57 | wm-gw-cli:nuc105 > sinks
Printing sinks of currently set gateway 'nuc105'
( sink0 )
18:09.59 | wm-gw-cli:nuc105 > set_sink
Current gateway is nuc105
0 :sink0 ( 1456854 )
1 : custom sink id
Please enter your sink selection [0]: 0
18:10.06 | wm-gw-cli:nuc105:sink0 > send_data 255 240 4294967295 60030000FF
Waiting response to request. Timeout is 30 seconds ..
Error got no reply for nuc105 in time. Time waited 30 secs.

**Software versions:**
 - OS: [e.g. Linux, Windows]
 - Python version: *e.g. 3.5, 3.7 ...*
 - Docker engine: *e.g. 18.06.0-ce, ...*
 - MQTT Broker vendor: *e.g. mosquitto, ...*
 - MQTT Broker version: *e.g. mosquitto, ...*
 - WNT version: if applicable
 - WPE version: if applicable

**Additional context**

**Screenshots**

**Comment by ErkkiSalonenW** [comment]
send_message function is generic function that sends data. Putting big timeout value makes feature unusable. We should consider writing a new command for the purpose. Then use case specific timeout and behavior is ok.

**Comment by ErkkiSalonenW** [comment]
Doing system design for feature now.
