### ISSUE TITLE
[BUG] CLI selection command doesn't work

### ISSUE THREAD

**Issue by vgeneves** [wirepas/backend-client#276]
the selection command doesn't work. The CLI hangs for ~30sec. Then print something went wrong  14:44.00 | wm-gw-cli:gw-prov-dev:sink1 > selection
Something went wrong:
14:44.57 | wm-gw-cli:gw-prov-dev:sink1 >

**Software versions:**
 - OS: Linux
 - Python version: 3.7
 - backend-client 1.3.2

**Comment by ErkkiSalonenW** [comment]
When i type selection. I get response. What commands have been executing before?

**Comment by ErkkiSalonenW** [comment]
Several improvements done. However there is architectural problem. If nodes diagnostics are off or no data data coming from nodes, enumeration does not work at all. Correct way to do invertory is to ping devices and collect responses. Closing issue for now.
