### ISSUE TITLE
[BUG] CLI set_config command doesn't work

### ISSUE THREAD

**Issue by vgeneves** [wirepas/backend-client#277]
the set_config command doesn't work (with any parameters) and prints an error : 
14:46.38 | wm-gw-cli:gw-prov-dev:sink1 > set_config node_address=2
Something went wrong:too many values to unpack (expected 2)

Software versions:

    OS: Linux
    Python version: 3.7
    backend-client 1.3.2

**Comment by JanneJuhola** [comment]
This seems to be open. Problem is here:
gateway.py:
   def do_set_config(self, line):
   ...
   for key, val in args:
->
   for key, val in args.items():

**Comment by ErkkiSalonenW** [comment]
Starting to check this one.

**Comment by ErkkiSalonenW** [comment]
Initial checks added in addition to Janne Juhola suggestion. Work continues.
