### ISSUE TITLE
[BUG] CLI command scratchpad_upload doesn't work

### ISSUE THREAD

**Issue by vgeneves** [wirepas/backend-client#289]
**Describe the bug**
The scratchpad_upload command doesn't work (with any parameters) and prints an error :

Error message:
scratchpad_upload filepath=image_wpc_stack.otap sequence=2
Something went wrong:expected str, bytes or os.PathLike object, not NoneType

**To Reproduce**
1. Select a gateway and a sink
2. launch "scratchpad_upload filepath=image_wpc_stack.otap sequence=2" command

**Software versions:**
 - OS: WSL2 (Ubuntu)
 - Python version: 3.7
 - Backend client : 1.3.2

**Comment by ErkkiSalonenW** [comment]
Hi. I will start checking this one. Could you possibly tell if this has been working on earlier versions such as 1.3.1?

**Comment by vgeneves** [comment]
Yes it was working with an earlier version. But I can't tell you which.
