### ISSUE TITLE
[BUG] Unable to set application configuration

### ISSUE THREAD

**Issue by teemupiiroinenwirepas** [wirepas/backend-client#296]
Configuration:
- WNT 3.0.1 backend
- Two gateways with multiple sinks on both

Backend-client version: 3255265c47ce3117073635bb42446f00fc52099f

Prints:

16:13.20 | wm-gw-cli > set_gateway
Listing current online gateways:
0 :wnttest1
1 :wnttest2
2 : custom gateway id
Please enter your gateway selection [0]: 0
16:13.34 | wm-gw-cli:wnttest1 > set_sink
Current gateway is wnttest1
0 :sink1 ( 3333 )
1 : custom sink id
Please enter your sink selection [0]: 0
16:13.40 | wm-gw-cli:wnttest1:sink1 > set_app_config 150 9000000000 30
Request error got no reply for wnttest1. Time waited 10 secs.

We were not able to set the appconfig with multiple tries, but WNT was able to set it without any problems.

**Comment by ErkkiSalonenW** [comment]
Fixed.
