### ISSUE TITLE
[BUG] Gaps in UL data to Mysql DB

### ISSUE THREAD

**Issue by kahaapal** [wirepas/backend-client#298]
**Describe the bug**
Seems that sql injector is not able to store all UL data packets to MySQL DB

**Expected behavior**
All data packets stored to MySQL DB

**To Reproduce**
1. Run KPI testing, high PPS UL cases, the higher, the longer gaps we get with data

**Additional context**

**Screenshots**

**Comment by ErkkiSalonenW** [comment]
What is data rate when it works and what id data rate roughly when messages starts pile up?

**Comment by ErkkiSalonenW** [comment]
Fix exists. Now under testing.
