### ISSUE TITLE
HTTP control cleanup

### ISSUE THREAD

**Issue by PFigs** [wirepas/backend-client#98]
The current HTTP control is in need of a cleanup and it should use existing framework classes instead of re implementing them. It would also be good to make away with the global variables it is currently making use of.

**Comment by JanneSiren** [comment]
Among other things #109 removes global variables from http control.

The implementation still has own SinkAndGatewayStatusObserver class to collect list of gateways and sinks. That implementation could be replaced with existing NetworkDiscovery class. Though for testing purposes (current usage of http control) the NetworkDiscovery class should limit gateway detection to happen only by subscription of "gw-event/status", and should not add gateways (or sinks) to list using any other means (e.g. from received data packages). This is to ensure that network discovery uses only means that are documented (WM-RM-128), and gw-event/status functionality gets fully tested. In case NetworkDiscovery class could limit gateway discovery to happen only via "gw-event/status", then SinkAndGatewayStatusObserver class could be replaced with NetworkDiscovery class, but before that it is not rationale to use NetworkDiscovery in http control.
